#target : Dependencies
#<TAB>Commands

Build : project_main.c workersActivities.c test_workersActivities.c unity.c
        gcc project_main.c workersActivities.c test_workersActivities.c unity.c -o workersActivities.out
Run : workersActivities.out
        ./workersActivities.out
Clean :
 	 rm -rf * .o *.out *.i *.s
