#target : Dependencies
#<TAB>Commands

Build : project_main.c workers.c test_workers.c unity.c
        gcc project_main.c workers.c test_workers.c unity.c -o calender.out
Run : workers.out
        ./workers.out
Clean :
      rm -rf * .o *.out *.i *.s
