#target : Dependencies
#<TAB>commands

Build : project_main.c workersActivities.c 
        gcc project_main.c WorkersActivities.c WorkersActivities.out
Run : WorkersActivities.out
	   ./WorkersActivities.out
Clean : 
		rm -rf * .o *.out *.i *.s
